version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "127.0.0.1:27017:27017"

  nodejs:
    depends_on:
      - mongodb
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: nodejs-container
    ports:
      - "3000:3000"

