version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"

  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: nodejs-container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
